name: Auto Grading

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Validate Solution
      env:
        EXPECTED_ANSWERS: ${{ secrets.EXPECTED_ANSWERS }}
      run: |
        if [ ! -f "solution.txt" ]; then
          echo "❌ Missing solution file!" && exit 1
        fi

        # Read expected answers from secret
        expected_answers=$(echo $EXPECTED_ANSWERS | jq -r '.[]')

        # Read answers from solution.txt
        IFS=$'\n' read -d '' -r -a answers < solution.txt

        # Validate answers
        index=0
        for expected_answer in $expected_answers; do
          if [[ "${answers[$index]}" != *"$expected_answer"* ]]; then
            echo "❌ Incorrect answer for question $((index+1))!" && exit 1
          fi
          index=$((index+1))
        done

        echo "✅ All answers are correct!"
